### ISSUE TITLE
Error when adding field

### ISSUE THREAD

**Issue by fortable1999** [whoosh-community/whoosh#421]
**[Original report](https://bitbucket.org/mchaput/whoosh/issue/421) by Michal Čihař (Bitbucket: [nijel](https://bitbucket.org/nijel), GitHub: [nijel](https://github.com/nijel)).**

----------------------------------------

I get an exception when trying to change existing index. It used to work fine in past, but stopped to work with update to 2.7.0.

The code I'm using:

```
#!python
    from whoosh.fields import TEXT
    from whoosh.filedb.filestore import FileStorage

    STORAGE = FileStorage('whoosh')
    index = STORAGE.open_index('source')
    if 'location' not in index.schema:
        index.add_field('location', TEXT)
```

Exception I get:

```
  File "/home/nijel/work/weblate/weblate/trans/search.py", line 121, in get_source_index
    index.add_field('location', TEXT)
  File "/usr/lib/python2.7/dist-packages/whoosh/index.py", line 235, in add_field
    w.add_field(fieldname, fieldspec)
  File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 600, in add_field
    super(SegmentWriter, self).add_field(fieldname, fieldspec, **kwargs)
  File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 276, in add_field
    self.schema.add(fieldname, fieldtype, **kwargs)
  File "/usr/lib/python2.7/dist-packages/whoosh/fields.py", line 1465, in add
    self._subfields[name] = sublist = []
AttributeError: 'Schema' object has no attribute '_subfields
```
